package itson.frames;

import java.awt.Font;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;

import javax.swing.Box;
import javax.swing.event.DocumentListener;

import itson.control.ControlFlujo;
import itson.dtos.BusquedaEventoDTO;
import itson.dtos.EventoDTO;
import itson.enums.EstadoEvento;
import itson.enums.ModalidadEvento;
import itson.fabrica.ObjetosNegocioFactory;
import itson.interfaces.IEventosBO;
import paneles.PnlEvento;

public class FrmEventos extends javax.swing.JFrame {

    /**
     * Creates new form FrmEventos
     */
    public FrmEventos() {
        initComponents();
        cargarFiltros();
        cargarEventos();
        cargarListener();
    }

    private void cargarFiltros() {
        ModalidadEvento[] modalidades = ModalidadEvento.values();
        for (ModalidadEvento modalidad : modalidades) {
            String strModalidad = modalidad.toString();
            String frmtModalidad = strModalidad.substring(0, 1).toUpperCase() + strModalidad.substring(1).toLowerCase();
            comboBoxModalidad.addItem(frmtModalidad);
        }
        EstadoEvento[] estados = EstadoEvento.values();
        for (EstadoEvento estado : estados) {
            String strEstado = estado.toString();
            String frmtEstado = strEstado.substring(0, 1).toUpperCase() + strEstado.substring(1).toLowerCase();
            comboBoxEstado.addItem(frmtEstado);
        }
    }

    private void cargarEventos() {
        IEventosBO eventosBO = ObjetosNegocioFactory.crearEventosBO();
        List<EventoDTO> eventos = eventosBO.obtenerEventos();
        cargarEventos(eventos);

    }

    private void cargarListener() {
        DocumentListener listener = new DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                buscar();
            }
        };

        txtBuscar.getDocument().addDocumentListener(listener);
        comboBoxModalidad.addItemListener(evt -> buscar());
        comboBoxEstado.addItemListener(evt -> buscar());
        fechaDesde.addPropertyChangeListener(evt -> buscar());
        fechaHasta.addPropertyChangeListener(evt -> buscar());

    }

    private void cargarEventos(List<EventoDTO> eventos) {
        boxPnlEventos.removeAll();
        for (EventoDTO evento : eventos) {
            PnlEvento pnlEvento = new PnlEvento(evento);
            boxPnlEventos.add(pnlEvento);
            boxPnlEventos.add(Box.createVerticalStrut(10));
        }
        boxPnlEventos.revalidate();
        boxPnlEventos.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlBotones = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblTitulo2 = new javax.swing.JLabel();
        comboBoxModalidad = new javax.swing.JComboBox<>();
        comboBoxEstado = new javax.swing.JComboBox<>();
        lblTitulo3 = new javax.swing.JLabel();
        lblTitulo4 = new javax.swing.JLabel();
        lblTitulo5 = new javax.swing.JLabel();
        fechaDesde = new com.github.lgooddatepicker.components.DatePicker();
        fechaHasta = new com.github.lgooddatepicker.components.DatePicker();
        lblTitulo6 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnVolver = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        scrollPaneEventos = new javax.swing.JScrollPane();
        boxPnlEventos = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 246, 247));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Eventos");
        lblTitulo.setFont(new Font("Inter", Font.PLAIN, 36));
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("Filtros de búsqueda");
        lblTitulo1.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo1.setForeground(new java.awt.Color(0, 0, 0));

        lblTitulo2.setText("Modalidad");
        lblTitulo2.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo2.setForeground(new java.awt.Color(0, 0, 0));

        comboBoxModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboBoxModalidad.setBackground(new java.awt.Color(244, 246, 247));
        comboBoxModalidad.setFont(new Font("Inter", Font.PLAIN, 16));
        comboBoxModalidad.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxModalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxModalidadItemStateChanged(evt);
            }
        });

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboBoxEstado.setBackground(new java.awt.Color(244, 246, 247));
        comboBoxEstado.setFont(new Font("Inter", Font.PLAIN, 16));
        comboBoxEstado.setForeground(new java.awt.Color(0, 0, 0));
        comboBoxEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxEstadoItemStateChanged(evt);
            }
        });

        lblTitulo3.setText("Estado");
        lblTitulo3.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo3.setForeground(new java.awt.Color(0, 0, 0));

        lblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo4.setText("Fechas");
        lblTitulo4.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo4.setForeground(new java.awt.Color(0, 0, 0));

        lblTitulo5.setText("Desde");
        lblTitulo5.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo5.setForeground(new java.awt.Color(0, 0, 0));

        fechaDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaDesdePropertyChange(evt);
            }
        });

        lblTitulo6.setText("Hasta");
        lblTitulo6.setFont(new Font("Inter", Font.PLAIN, 18));
        lblTitulo6.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(comboBoxModalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(comboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(lblTitulo5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(fechaDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(fechaHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtBuscar.setText("Buscar...");
        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setFont(new Font("Inter", Font.PLAIN, 16));
        txtBuscar.setForeground(new java.awt.Color(100, 100, 100));
        txtBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBuscarMouseExited(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\image 4.png")); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        btnNuevo.setText("Nuevo Evento");
        btnNuevo.setBackground(new java.awt.Color(66, 165, 245));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setFont(new Font("Inter", Font.PLAIN, 18));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setInheritsPopupMenu(true);

        scrollPaneEventos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPaneEventos.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneEventos.setBorder(null);
        scrollPaneEventos.setForeground(new java.awt.Color(255, 255, 255));

        boxPnlEventos.setBackground(new java.awt.Color(255, 255, 255));
        boxPnlEventos.setForeground(new java.awt.Color(255, 255, 255));
        boxPnlEventos.setLayout(new javax.swing.BoxLayout(boxPnlEventos, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneEventos.setViewportView(boxPnlEventos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneEventos, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(scrollPaneEventos)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnVolver)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(11, 11, 11)))
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxModalidadItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboBoxModalidadItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {

        }
    }// GEN-LAST:event_comboBoxModalidadItemStateChanged

    private boolean seleccionado = false;

    private void txtBuscarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtBuscarMouseClicked
        seleccionado = true;
        txtBuscar.setText("");
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
    }// GEN-LAST:event_txtBuscarMouseClicked

    private void txtBuscarMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtBuscarMouseEntered
        if (!seleccionado) {
            txtBuscar.setText("");
        }
    }// GEN-LAST:event_txtBuscarMouseEntered

    private void txtBuscarMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtBuscarMouseExited
        if (!seleccionado) {
            txtBuscar.setText("Buscar...");
        }
    }// GEN-LAST:event_txtBuscarMouseExited

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnVolverMouseClicked
        ControlFlujo.iniciarFlujo();
        this.dispose();
    }// GEN-LAST:event_btnVolverMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevoActionPerformed
        ControlFlujo.mostrarFrame(new FrmRegistrarEvento());
        this.dispose();
    }// GEN-LAST:event_btnNuevoActionPerformed

    private void comboBoxEstadoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_comboBoxEstadoItemStateChanged
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxEstadoItemStateChanged

    private void fechaDesdePropertyChange(java.beans.PropertyChangeEvent evt) {// GEN-FIRST:event_fechaDesdePropertyChange
        // TODO add your handling code here:
    }// GEN-LAST:event_fechaDesdePropertyChange

    private void buscar() {
        String filtro = txtBuscar.getText();
        String modalidadStr = comboBoxModalidad.getSelectedItem().toString().toUpperCase();
        String estadoStr = comboBoxEstado.getSelectedItem().toString().toUpperCase();
        ModalidadEvento modalidad = null;
        if (!modalidadStr.equals("SELECCIONAR...")) {
            modalidad = ModalidadEvento.valueOf(modalidadStr);
        } 
        EstadoEvento estado = null;
        if (!estadoStr.equals("SELECCIONAR...")) {
            estado = EstadoEvento.valueOf(estadoStr);
        }
        if (filtro.isEmpty()) {
            filtro = null;
        }
        Calendar fechaDesde = toCalendar(this.fechaDesde.getDate());
        Calendar fechaHasta = toCalendar(this.fechaHasta.getDate());
        
        BusquedaEventoDTO busquedaEventoDTO = new BusquedaEventoDTO(filtro, fechaDesde, fechaHasta,
                modalidad, estado);
        IEventosBO eventosBO = ObjetosNegocioFactory.crearEventosBO();
        List<EventoDTO> eventos = eventosBO.buscarEventosPorFiltro(busquedaEventoDTO);
        cargarEventos(eventos);
    }

    private Calendar toCalendar(LocalDate date) {
        if (date == null) {
            return null;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.set(date.getYear(), date.getMonthValue() - 1, date.getDayOfMonth());
        return calendar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxPnlEventos;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JComboBox<String> comboBoxModalidad;
    private com.github.lgooddatepicker.components.DatePicker fechaDesde;
    private com.github.lgooddatepicker.components.DatePicker fechaHasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JLabel lblTitulo4;
    private javax.swing.JLabel lblTitulo5;
    private javax.swing.JLabel lblTitulo6;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JScrollPane scrollPaneEventos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
