package itson.frames;

import java.awt.Font;
import java.time.LocalDate;
import java.util.Calendar;

import javax.swing.JOptionPane;

import itson.control.ControlFlujo;
import itson.control.Formateador;
import itson.dtos.EventoDTO;
import itson.dtos.ResponsableDTO;
import itson.enums.EstadoEvento;
import itson.enums.ModalidadEvento;
import itson.excepciones.NegocioException;
import itson.fabrica.ObjetosNegocioFactory;
import itson.interfaces.IResponsablesBO;

public class FrmInfoEvento extends javax.swing.JFrame {

    private EventoDTO evento;
    private int opcion;

    public static final int OPCION_VER = 1;
    public static final int OPCION_EDITAR = 2;

    public FrmInfoEvento(EventoDTO evento, int opcion) {
        this.evento = evento;
        this.opcion = opcion;
        initComponents();
        cargarDatosEvento();
    }

    private void cargarDatosEvento() {
        txtTitulo.setText(evento.getTitulo());
        txtDescripcion.setText(evento.getDescripcion());
        fechaInicio.setDate(toLocalDate(evento.getFechaInicio()));
        fechaFin.setDate(toLocalDate(evento.getFechaFin()));
        IResponsablesBO responsablesBO = ObjetosNegocioFactory.crearResponsablesBO();
        try {
            ResponsableDTO responsable = responsablesBO.obtenerResponsablePorId(evento.getResponsableId());
            lblOrganizador.setText(Formateador.formatearNombre(responsable.getNombre(), responsable.getApellidoPaterno(), responsable.getApellidoMaterno()));
        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el responsable: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        comboBoxModalidad.removeAllItems();
        comboBoxModalidad.addItem(Formateador.formatearCap(evento.getModalidad().toString()));
        comboBoxEstado.removeAllItems();
        comboBoxEstado.addItem(Formateador.formatearCap(evento.getEstado().toString()));

        if (opcion == OPCION_VER) {
            txtTitulo.setEditable(false);
            txtDescripcion.setEditable(false);
            fechaInicio.setEnabled(false);
            fechaFin.setEnabled(false);
            comboBoxModalidad.setEditable(false);
            comboBoxEstado.setEditable(false);
            btnFinalizado.setVisible(false);
            btnModificarEvento.setVisible(false);
        } else {
            comboBoxModalidad.removeAll();
            ModalidadEvento[] modalidades = ModalidadEvento.values();
            for (ModalidadEvento modalidad : modalidades) {
                comboBoxModalidad.addItem(Formateador.formatearCap(modalidad.toString()));
            }
            comboBoxModalidad.setSelectedItem(Formateador.formatearCap(evento.getModalidad().toString()));
            comboBoxEstado.removeAll();
            EstadoEvento[] estados = EstadoEvento.values();
            for (EstadoEvento estado : estados) {
                comboBoxEstado.addItem(Formateador.formatearCap(estado.toString()));
            }
            comboBoxEstado.setSelectedItem(Formateador.formatearCap(evento.getEstado().toString()));
        }
    }

    private LocalDate toLocalDate(Calendar calendar) {
        return LocalDate.of(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH) + 1,
                calendar.get(Calendar.DAY_OF_MONTH));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblNombre4 = new javax.swing.JLabel();
        comboBoxModalidad = new javax.swing.JComboBox<>();
        lblNombre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        lblNombre5 = new javax.swing.JLabel();
        fechaFin = new com.github.lgooddatepicker.components.DatePicker();
        fechaInicio = new com.github.lgooddatepicker.components.DatePicker();
        lblNombre6 = new javax.swing.JLabel();
        lblNombre7 = new javax.swing.JLabel();
        lblOrganizador = new javax.swing.JLabel();
        btnVerActividades = new javax.swing.JButton();
        lblNombre8 = new javax.swing.JLabel();
        comboBoxEstado = new javax.swing.JComboBox<>();
        btnFinalizado = new javax.swing.JButton();
        btnModificarEvento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 246, 247));

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Visualizar Evento");
        lblTitulo.setFont(new Font("Inter", Font.PLAIN, 36));
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));

        btnVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\pc\\Downloads\\image 4.png")); // NOI18N
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblNombre.setText("Título");
        lblNombre.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));

        txtTitulo.setFont(new Font("Inter", Font.PLAIN, 16));
        txtTitulo.setBackground(new java.awt.Color(244, 246, 247));
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));

        lblNombre4.setText("Modalidad");
        lblNombre4.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre4.setForeground(new java.awt.Color(0, 0, 0));

        comboBoxModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboBoxModalidad.setBackground(new java.awt.Color(244, 246, 247));
        comboBoxModalidad.setFont(new Font("Inter", Font.PLAIN, 16));
        comboBoxModalidad.setForeground(new java.awt.Color(0, 0, 0));

        lblNombre1.setText("Descripción");
        lblNombre1.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre1.setForeground(new java.awt.Color(0, 0, 0));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new Font("Inter", Font.PLAIN, 16));
        txtDescripcion.setRows(5);
        txtDescripcion.setBackground(new java.awt.Color(244, 246, 247));
        jScrollPane1.setViewportView(txtDescripcion);

        lblNombre5.setText("Fecha de Inicio");
        lblNombre5.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre5.setForeground(new java.awt.Color(0, 0, 0));

        lblNombre6.setText("Fecha Final");
        lblNombre6.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre6.setForeground(new java.awt.Color(0, 0, 0));

        lblNombre7.setText("Organizador:");
        lblNombre7.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre7.setForeground(new java.awt.Color(0, 0, 0));

        lblOrganizador.setText("...");
        lblOrganizador.setFont(new Font("Inter", Font.PLAIN, 16));
        lblOrganizador.setForeground(new java.awt.Color(0, 0, 0));

        btnVerActividades.setText("Ver Actividades");
        btnVerActividades.setBackground(new java.awt.Color(66, 165, 245));
        btnVerActividades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerActividades.setFont(new Font("Inter", Font.PLAIN, 18));
        btnVerActividades.setForeground(new java.awt.Color(255, 255, 255));
        btnVerActividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActividadesActionPerformed(evt);
            }
        });

        lblNombre8.setText("Estado");
        lblNombre8.setFont(new Font("Inter", Font.PLAIN, 16));
        lblNombre8.setForeground(new java.awt.Color(0, 0, 0));

        comboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        comboBoxEstado.setBackground(new java.awt.Color(244, 246, 247));
        comboBoxEstado.setFont(new Font("Inter", Font.PLAIN, 16));
        comboBoxEstado.setForeground(new java.awt.Color(0, 0, 0));

        btnFinalizado.setText("Marcar como finalizado");
        btnFinalizado.setBackground(new java.awt.Color(66, 165, 245));
        btnFinalizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizado.setFont(new Font("Inter", Font.PLAIN, 18));
        btnFinalizado.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVerActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(lblNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(lblNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOrganizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblOrganizador, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addComponent(btnVerActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        btnModificarEvento.setText("Modificar Evento");
        btnModificarEvento.setBackground(new java.awt.Color(66, 165, 245));
        btnModificarEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificarEvento.setFont(new Font("Inter", Font.PLAIN, 18));
        btnModificarEvento.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEventoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnVolver)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnModificarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        ControlFlujo.mostrarFrame(new FrmEventos());
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    private void btnVerActividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActividadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActividadesActionPerformed

    private void btnFinalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizadoActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea marcar el evento como finalizado?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                ObjetosNegocioFactory.crearEventosBO().modificarEstadoEvento(evento.getId(), evento.getEstado());
                JOptionPane.showMessageDialog(this, "Evento marcado como finalizado.");
                ControlFlujo.mostrarFrame(new FrmEventos());
                this.dispose();
            } catch (NegocioException e) {
                JOptionPane.showMessageDialog(this, "Error al marcar el evento como finalizado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnFinalizadoActionPerformed

    private void btnModificarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActividades1ActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea modificar el evento?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                EventoDTO eventoModificado = new EventoDTO(
                        evento.getId(),
                        txtTitulo.getText(),
                        txtDescripcion.getText(),
                        Formateador.toCalendar(fechaInicio.getDate()),
                        Formateador.toCalendar(fechaFin.getDate()),
                        evento.getEstado(),
                        evento.getModalidad(),
                        null,
                        evento.getResponsableId()
                );
                ObjetosNegocioFactory.crearEventosBO().modificarEvento(eventoModificado);
                JOptionPane.showMessageDialog(this, "Evento modificado correctamente.");
                ControlFlujo.mostrarFrame(new FrmEventos());
                this.dispose();
            } catch (NegocioException e) {
                JOptionPane.showMessageDialog(this, "Error al modificar el evento: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVerActividades1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizado;
    private javax.swing.JButton btnModificarEvento;
    private javax.swing.JButton btnVerActividades;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JComboBox<String> comboBoxEstado;
    private javax.swing.JComboBox<String> comboBoxModalidad;
    private com.github.lgooddatepicker.components.DatePicker fechaFin;
    private com.github.lgooddatepicker.components.DatePicker fechaInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre4;
    private javax.swing.JLabel lblNombre5;
    private javax.swing.JLabel lblNombre6;
    private javax.swing.JLabel lblNombre7;
    private javax.swing.JLabel lblNombre8;
    private javax.swing.JLabel lblOrganizador;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
