package itson.paneles;

import java.awt.Font;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import itson.control.ControlFlujo;
import itson.control.Formateador;
import itson.dtos.EventoDTO;
import itson.dtos.ParticipanteDTO;
import itson.enums.EstadoEvento;
import itson.frames.FrmActividades;
import itson.frames.FrmInfoEvento;

public class PnlEvento extends javax.swing.JPanel {

    private EventoDTO evento;
    private List<ParticipanteDTO> participantes;

    /**
     * Creates new form PnlEvento
     */
    public PnlEvento(EventoDTO evento) {
        this.evento = evento;
        initComponents();
        cargarDatosEvento();
    }
    /**
     * Creates new form PnlEvento
     */
    public PnlEvento(EventoDTO evento, List<ParticipanteDTO> participantes) {
        this.participantes = participantes;
        this.evento = evento;
        initComponents();
        cargarDatosEvento();
    }

    private void cargarDatosEvento(){
        lblTitulo.setText(evento.getTitulo());
        lblFechaInicio.setText("Fecha Inicio: " + Formateador.formatearFecha(evento.getFechaInicio()));
        lblFechaFin.setText("Fecha Fin: " + Formateador.formatearFecha(evento.getFechaFin()));
        lblModalidad.setText("Modalidad: " + Formateador.formatearCap(evento.getModalidad().toString()));
        lblEstado.setText("Estado: " + Formateador.formatearCap(evento.getEstado().toString()));
        if(participantes != null){
            btnModificar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFin = new javax.swing.JLabel();
        lblModalidad = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        btnModificar = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(437, 169));
        setMinimumSize(new java.awt.Dimension(437, 169));

        jPanel1.setBackground(new java.awt.Color(244, 246, 247));
        jPanel1.setMaximumSize(new java.awt.Dimension(437, 159));
        jPanel1.setMinimumSize(new java.awt.Dimension(437, 159));

        lblTitulo.setFont(new Font("Inter", Font.PLAIN, 14));
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setText("Nombre Evento");

        lblFechaInicio.setFont(new Font("Inter", Font.PLAIN, 14));
        lblFechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaInicio.setText("Fecha Inicio:");

        lblFechaFin.setFont(new Font("Inter", Font.PLAIN, 14));
        lblFechaFin.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaFin.setText("Fecha Fin:");

        lblModalidad.setFont(new Font("Inter", Font.PLAIN, 14));
        lblModalidad.setForeground(new java.awt.Color(0, 0, 0));
        lblModalidad.setText("Modalidad:");

        lblEstado.setFont(new Font("Inter", Font.PLAIN, 14));
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setText("Estado:");

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnVer.png"))); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnModificar.png"))); // NOI18N
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                    .addComponent(lblFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModalidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnVer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaFin)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblModalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstado)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificar)
                            .addComponent(btnVer))
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if(participantes != null){
            ControlFlujo.mostrarFrame(new FrmActividades(this.evento, FrmActividades.OPCION_ASOCIAR, participantes));
        } else {
            ControlFlujo.mostrarFrame(new FrmInfoEvento(this.evento, FrmInfoEvento.OPCION_VER));
        }
        frame.dispose();
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        if(evento.getEstado().equals(EstadoEvento.FINALIZADO)){
            JOptionPane.showMessageDialog(this, "No se puede editar un evento finalizado", "Evento Finalizado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        ControlFlujo.mostrarFrame(new FrmInfoEvento(this.evento, FrmInfoEvento.OPCION_EDITAR));
        frame.dispose();
    }//GEN-LAST:event_btnModificarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnModificar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaFin;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
