package itson.paneles;

import java.awt.Font;

import itson.dtos.ParticipanteDTO;
import itson.reportes.generadores.GeneradorHistorialActividades;

public class PnlParticipante extends javax.swing.JPanel {

    private ParticipanteDTO participanteDTO;
    private boolean seleccionado;

    /**
     * Creates new form PnlParticipante
     */
    public PnlParticipante(ParticipanteDTO participanteDTO) {
        this.participanteDTO = participanteDTO;
        initComponents();
        cargarDatosParticipante();
    }
    
    private void cargarDatosParticipante() {
        jLabel1.setText(participanteDTO.getNombre() + " " + participanteDTO.getApellidoPaterno() + " " + participanteDTO.getApellidoMaterno());
        jLabel2.setText("Correo: "+participanteDTO.getCorreo());
        jLabel3.setText("Tipo Participante: " + participanteDTO.getTipoParticipante());
        jLabel4.setText("Dependencia: " + participanteDTO.getDependencia());
        jLabel5.setText("Número de Control: " + participanteDTO.getNumeroControl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        checkBoxSeleccionado = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(244, 246, 247));
        setMaximumSize(new java.awt.Dimension(437, 159));
        setMinimumSize(new java.awt.Dimension(437, 159));

        jLabel1.setFont(new Font("Inter", Font.PLAIN, 14));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre Completo");

        jLabel2.setFont(new Font("Inter", Font.PLAIN, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Correo: ");

        jLabel3.setFont(new Font("Inter", Font.PLAIN, 14));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo Participante: Estudiante");

        jLabel4.setFont(new Font("Inter", Font.PLAIN, 14));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Dependencia: ");

        jLabel5.setFont(new Font("Inter", Font.PLAIN, 14));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Número de Control: ");

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnVer.png"))); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });

        checkBoxSeleccionado.setFont(new Font("Inter", Font.PLAIN, 14));
        checkBoxSeleccionado.setForeground(new java.awt.Color(0, 0, 0));
        checkBoxSeleccionado.setText("Seleccionar");
        checkBoxSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkBoxSeleccionado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(checkBoxSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(btnVer))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxSeleccionadoActionPerformed
        seleccionado = checkBoxSeleccionado.isSelected();
        if (seleccionado) {
            checkBoxSeleccionado.setText("Desmarcar");
        } else {
            checkBoxSeleccionado.setText("Seleccionar");
        }
    }//GEN-LAST:event_checkBoxSeleccionadoActionPerformed

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        GeneradorHistorialActividades generador = new GeneradorHistorialActividades();
        generador.generarHistorialActividades(participanteDTO.getId());
    }//GEN-LAST:event_btnVerMouseClicked

    public boolean isSeleccionado() {
        return checkBoxSeleccionado.isSelected();
    }

    public ParticipanteDTO getParticipante() {
        return participanteDTO;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnVer;
    private javax.swing.JCheckBox checkBoxSeleccionado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
